services:
  # A Docker web service
  - type: web
    name: myapp
    env: docker
    buildCommand: .venv/bin/myapp manage migrate --no-input
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: main # optional (defaults to master)
    numInstances: 3 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-db
          property: connectionString
